# This is a basic workflow that is manually triggered

name: Minify Files

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  minify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
    - uses: actions/checkout@v3

    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1

  # Auto commits minified files to the repository
  # Ignore it if you don't want to commit the files to the repository 
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
